---
title: "191024_inclass"
author: "Gavin Ko"
date: "10/24/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(rvest)
```

Write some functions.

```{r}
set.seed(1)
x = rnorm(n = 30, mean = 4, sd = 2.3)
x_again = rnorm(n = 30, mean = 2, sd = 1.6)
y = rnorm(n = 30, mean = 1.58, sd = 1.58)


z = (x - mean(x)) / sd(x)
z_again = (x_again - mean(x_again)) / sd(x_again)

```

So complicated, let's write function instead.

```{r}
# input in the first parenthesis
z_score = function(x) {
  
# conditional execution, make sure it breaks at the right time
  if (!is.numeric(x)) {
    stop("you are doing something wrong")
  } else if (length(x) <= 3) {
    stop("hey the data length is too small")
  }
  
  (x - mean(x)) / sd(x)
}

z_score(x_again)
z_score(y)
```

Test another function.
```{r}
mean_sd_function = function(input_x) {
  
  if (!is.numeric(x)) {
  stop("you are doing something wrong")
  
  } else if (length(x) <= 3) {
    stop("hey the data length is too small")
    }
  
  list(
  mean_x = mean(input_x),
  sd_x = sd(input_x),
  zscore = (input_x - mean(input_x)) / sd(input_x) )
  
}

mean_sd_function(y)

```

Multiple inputs

```{r}
# we can set default settings for each value
sim_regression = function(n = 30, beta0 = 2, beta1 = 3) {
  
  sim_data = tibble(
    x = rnorm(n, mean = 1, sd = 1),
    y = beta0 + beta1 * x + rnorm(n, mean = 0, sd = 1)
  )

  ls_fit = lm(y ~ x, data = sim_data)

  tibble(
  beta0_hat = coef(ls_fit)[1], # for intercept
  beta1_hat = coef(ls_fit)[2]  # for the first coefficient
  )
  
}

sim_regression(n = 14, beta0 = 24)
```









